//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBanking_v1.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InternetBanking_v1.App_LocalResources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Statement.
        /// </summary>
        public static string Account_Statement {
            get {
                return ResourceManager.GetString("Account_Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Already Exists, Please add different Account Number...
        /// </summary>
        public static string AccountAlreadyExistsError {
            get {
                return ResourceManager.GetString("AccountAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string AccountDesc {
            get {
                return ResourceManager.GetString("AccountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name is Required.
        /// </summary>
        public static string AccountNameRequired {
            get {
                return ResourceManager.GetString("AccountNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number.
        /// </summary>
        public static string AccountNo {
            get {
                return ResourceManager.GetString("AccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts and status.
        /// </summary>
        public static string Accounts_and_status {
            get {
                return ResourceManager.GetString("Accounts_and_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Account Number to view Statement.
        /// </summary>
        public static string AccStatementBoxHeader {
            get {
                return ResourceManager.GetString("AccStatementBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccSummary_AccountNumber {
            get {
                return ResourceManager.GetString("AccSummary_AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Accounts.
        /// </summary>
        public static string AccSummary_BoxHeader {
            get {
                return ResourceManager.GetString("AccSummary_BoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string AccSummary_Details {
            get {
                return ResourceManager.GetString("AccSummary_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccSummary_Parent {
            get {
                return ResourceManager.GetString("AccSummary_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Summary.
        /// </summary>
        public static string AccSummary_Title {
            get {
                return ResourceManager.GetString("AccSummary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        public static string AddAccountButton {
            get {
                return ResourceManager.GetString("AddAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        public static string AddAccountTitle {
            get {
                return ResourceManager.GetString("AddAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Favorite Cards.
        /// </summary>
        public static string AddCardBoxHeader {
            get {
                return ResourceManager.GetString("AddCardBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Card.
        /// </summary>
        public static string AddCardButton {
            get {
                return ResourceManager.GetString("AddCardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Card.
        /// </summary>
        public static string AddCardTitle {
            get {
                return ResourceManager.GetString("AddCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Your Favorite Meters.
        /// </summary>
        public static string AddMeterBoxHeader {
            get {
                return ResourceManager.GetString("AddMeterBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Meter.
        /// </summary>
        public static string AddMeterButton {
            get {
                return ResourceManager.GetString("AddMeterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Meter.
        /// </summary>
        public static string AddMeterTitle {
            get {
                return ResourceManager.GetString("AddMeterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your Favorite Phone Number.
        /// </summary>
        public static string AddPhoneBoxHeader {
            get {
                return ResourceManager.GetString("AddPhoneBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Phone.
        /// </summary>
        public static string AddPhoneButton {
            get {
                return ResourceManager.GetString("AddPhoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Favorite Phone Number.
        /// </summary>
        public static string AddPhoneTitle {
            get {
                return ResourceManager.GetString("AddPhoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is Required.
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Transactions.
        /// </summary>
        public static string AllTransactions {
            get {
                return ResourceManager.GetString("AllTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Transfers.
        /// </summary>
        public static string AllTransfers {
            get {
                return ResourceManager.GetString("AllTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is Required.
        /// </summary>
        public static string AmountRequired {
            get {
                return ResourceManager.GetString("AmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string arabiName {
            get {
                return ResourceManager.GetString("arabiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize Transfer.
        /// </summary>
        public static string AuthorizeTransfer {
            get {
                return ResourceManager.GetString("AuthorizeTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Details.
        /// </summary>
        public static string AuthorizeTransferDetails {
            get {
                return ResourceManager.GetString("AuthorizeTransferDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benifitiary Name.
        /// </summary>
        public static string BenifitiaryName {
            get {
                return ResourceManager.GetString("BenifitiaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benifitiary Phone.
        /// </summary>
        public static string BenifitiaryPhone {
            get {
                return ResourceManager.GetString("BenifitiaryPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Bill Information.
        /// </summary>
        public static string Bill_Information {
            get {
                return ResourceManager.GetString("Bill_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Amount.
        /// </summary>
        public static string BillAmount {
            get {
                return ResourceManager.GetString("BillAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biller Name.
        /// </summary>
        public static string BillerName {
            get {
                return ResourceManager.GetString("BillerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biller Name is Required.
        /// </summary>
        public static string BillerNameRequired {
            get {
                return ResourceManager.GetString("BillerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Your account is blocked please contact your branch.
        /// </summary>
        public static string BlockedAccountMessage {
            get {
                return ResourceManager.GetString("BlockedAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PDF.
        /// </summary>
        public static string Button_Create_PDF {
            get {
                return ResourceManager.GetString("Button_Create_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Excel.
        /// </summary>
        public static string Button_Export_Excel {
            get {
                return ResourceManager.GetString("Button_Export_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Bill.
        /// </summary>
        public static string Button_GetBill {
            get {
                return ResourceManager.GetString("Button_GetBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string ButtonTransfer {
            get {
                return ResourceManager.GetString("ButtonTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card ID.
        /// </summary>
        public static string CardID {
            get {
                return ResourceManager.GetString("CardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardless Transfer.
        /// </summary>
        public static string CardlessTransfer {
            get {
                return ResourceManager.GetString("CardlessTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Name.
        /// </summary>
        public static string CardName {
            get {
                return ResourceManager.GetString("CardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Card Name.
        /// </summary>
        public static string CardNameRequired {
            get {
                return ResourceManager.GetString("CardNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Card Number.
        /// </summary>
        public static string CardNumberRequired {
            get {
                return ResourceManager.GetString("CardNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Your Password.
        /// </summary>
        public static string Change_Your_Password {
            get {
                return ResourceManager.GetString("Change_Your_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Number.
        /// </summary>
        public static string CheqNum {
            get {
                return ResourceManager.GetString("CheqNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Status.
        /// </summary>
        public static string ChequeBookStatusBtn {
            get {
                return ResourceManager.GetString("ChequeBookStatusBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque-Book Status.
        /// </summary>
        public static string ChequeBookStatusTitle {
            get {
                return ResourceManager.GetString("ChequeBookStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Date.
        /// </summary>
        public static string ChequeDate {
            get {
                return ResourceManager.GetString("ChequeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Number is Required.
        /// </summary>
        public static string ChequeNumberRequired {
            get {
                return ResourceManager.GetString("ChequeNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check Cheque Range.
        /// </summary>
        public static string ChequeRangeError {
            get {
                return ResourceManager.GetString("ChequeRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Status.
        /// </summary>
        public static string ChequeStatus {
            get {
                return ResourceManager.GetString("ChequeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose a different Account.
        /// </summary>
        public static string ChooseDifferentAccountAlert {
            get {
                return ResourceManager.GetString("ChooseDifferentAccountAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Card.
        /// </summary>
        public static string chooseFavoriteCard {
            get {
                return ResourceManager.GetString("chooseFavoriteCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your Cheque Status.
        /// </summary>
        public static string ChqStatus_BoxHeader {
            get {
                return ResourceManager.GetString("ChqStatus_BoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Status.
        /// </summary>
        public static string ChqStatus_Title {
            get {
                return ResourceManager.GetString("ChqStatus_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry Connectivity Issue.. please try again later.
        /// </summary>
        public static string ConnectivityErrorMessage {
            get {
                return ResourceManager.GetString("ConnectivityErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity Issue, Please Try Again Later.
        /// </summary>
        public static string ConnectivityIssue {
            get {
                return ResourceManager.GetString("ConnectivityIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUsTitle {
            get {
                return ResourceManager.GetString("ContactUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contract Number.
        /// </summary>
        public static string contractNumber {
            get {
                return ResourceManager.GetString("contractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corprate.
        /// </summary>
        public static string Corprate_Parent {
            get {
                return ResourceManager.GetString("Corprate_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course ID.
        /// </summary>
        public static string CourseID {
            get {
                return ResourceManager.GetString("CourseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current IPIN.
        /// </summary>
        public static string CurrentIPIN {
            get {
                return ResourceManager.GetString("CurrentIPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current IPIN is Required.
        /// </summary>
        public static string CurrentIPINRequired {
            get {
                return ResourceManager.GetString("CurrentIPINRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Passowrd.
        /// </summary>
        public static string CurrentPassowrd {
            get {
                return ResourceManager.GetString("CurrentPassowrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plese Enter Current Password.
        /// </summary>
        public static string CurrentPassowrdRequired {
            get {
                return ResourceManager.GetString("CurrentPassowrdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My bill.
        /// </summary>
        public static string Customs_bill {
            get {
                return ResourceManager.GetString("Customs_bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customs billPayment.
        /// </summary>
        public static string Customs_Title {
            get {
                return ResourceManager.GetString("Customs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customs Payment Service.
        /// </summary>
        public static string CustomsPayment_BoxHeader {
            get {
                return ResourceManager.GetString("CustomsPayment_BoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customs Payment.
        /// </summary>
        public static string CustomsPayment_Title {
            get {
                return ResourceManager.GetString("CustomsPayment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Transactions.
        /// </summary>
        public static string Dash_LatestTrans {
            get {
                return ResourceManager.GetString("Dash_LatestTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        public static string Dash_MoreInfo {
            get {
                return ResourceManager.GetString("Dash_MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Balance.
        /// </summary>
        public static string Dash_PrimaryBalance {
            get {
                return ResourceManager.GetString("Dash_PrimaryBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfers.
        /// </summary>
        public static string Dash_Transfer_sub {
            get {
                return ResourceManager.GetString("Dash_Transfer_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Summary.
        /// </summary>
        public static string Dash_TransferSummary {
            get {
                return ResourceManager.GetString("Dash_TransferSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Accounts.
        /// </summary>
        public static string Dash_UserAccounts {
            get {
                return ResourceManager.GetString("Dash_UserAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Your account is De-Activated or Deleted please contact your branch.
        /// </summary>
        public static string DeActivatedAccountMessage {
            get {
                return ResourceManager.GetString("DeActivatedAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Declarant Number.
        /// </summary>
        public static string DeclarntRequired {
            get {
                return ResourceManager.GetString("DeclarntRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Card.
        /// </summary>
        public static string EditCard {
            get {
                return ResourceManager.GetString("EditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Meter Information.
        /// </summary>
        public static string EditMeterTitle {
            get {
                return ResourceManager.GetString("EditMeterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Phone information.
        /// </summary>
        public static string EditPhoneTitle {
            get {
                return ResourceManager.GetString("EditPhoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number.
        /// </summary>
        public static string EGov_InvoiceNo {
            get {
                return ResourceManager.GetString("EGov_InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number is Required.
        /// </summary>
        public static string EGov_InvoiceNo_Required {
            get {
                return ResourceManager.GetString("EGov_InvoiceNo_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Gov Payment Service.
        /// </summary>
        public static string EGovBoxHeader {
            get {
                return ResourceManager.GetString("EGovBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Gov payment.
        /// </summary>
        public static string EGovTitle {
            get {
                return ResourceManager.GetString("EGovTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity Information.
        /// </summary>
        public static string Electricity_Information {
            get {
                return ResourceManager.GetString("Electricity_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity Payment.
        /// </summary>
        public static string Electricity_Payment_BoxHeader {
            get {
                return ResourceManager.GetString("Electricity_Payment_BoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity Payment.
        /// </summary>
        public static string Electricity_Title {
            get {
                return ResourceManager.GetString("Electricity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity Information.
        /// </summary>
        public static string ElectricityInformation {
            get {
                return ResourceManager.GetString("ElectricityInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Write a valid e-mail.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is Required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string englishName {
            get {
                return ResourceManager.GetString("englishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Phone ID.
        /// </summary>
        public static string FavoritePhoneID {
            get {
                return ResourceManager.GetString("FavoritePhoneID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Name.
        /// </summary>
        public static string FavoritePhoneName {
            get {
                return ResourceManager.GetString("FavoritePhoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Name is Required.
        /// </summary>
        public static string FavoritePhoneNameRequired {
            get {
                return ResourceManager.GetString("FavoritePhoneNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Phone Number.
        /// </summary>
        public static string FavoritePhoneNumber {
            get {
                return ResourceManager.GetString("FavoritePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Phone Number is Required.
        /// </summary>
        public static string FavoritePhoneNumberRequired {
            get {
                return ResourceManager.GetString("FavoritePhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Date.
        /// </summary>
        public static string FileDate {
            get {
                return ResourceManager.GetString("FileDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File ID.
        /// </summary>
        public static string FileID {
            get {
                return ResourceManager.GetString("FileID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Kind.
        /// </summary>
        public static string FormKind {
            get {
                return ResourceManager.GetString("FormKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Number.
        /// </summary>
        public static string formNo {
            get {
                return ResourceManager.GetString("formNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Account Number.
        /// </summary>
        public static string FromAccountNo {
            get {
                return ResourceManager.GetString("FromAccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date is Required.
        /// </summary>
        public static string FromDateRequired {
            get {
                return ResourceManager.GetString("FromDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From File.
        /// </summary>
        public static string FromFile {
            get {
                return ResourceManager.GetString("FromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Account Number.
        /// </summary>
        public static string FullAccountNumber {
            get {
                return ResourceManager.GetString("FullAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Type Options.
        /// </summary>
        public static string Header_Statement_Type_Options {
            get {
                return ResourceManager.GetString("Header_Statement_Type_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; Support.
        /// </summary>
        public static string HelpAndSupportTitle {
            get {
                return ResourceManager.GetString("HelpAndSupportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Check.
        /// </summary>
        public static string InvestmentBoxHeader {
            get {
                return ResourceManager.GetString("InvestmentBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment.
        /// </summary>
        public static string InvestmentTitle {
            get {
                return ResourceManager.GetString("InvestmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPIN.
        /// </summary>
        public static string IPIN {
            get {
                return ResourceManager.GetString("IPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPIN is Required.
        /// </summary>
        public static string IPINRequired {
            get {
                return ResourceManager.GetString("IPINRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there is an issue with your Account Please contact your branch.
        /// </summary>
        public static string IssueWithAccountMessage {
            get {
                return ResourceManager.GetString("IssueWithAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string Lable_AccountNumber {
            get {
                return ResourceManager.GetString("Lable_AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Lable_Amount {
            get {
                return ResourceManager.GetString("Lable_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Name.
        /// </summary>
        public static string Lable_CardName {
            get {
                return ResourceManager.GetString("Lable_CardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Card.
        /// </summary>
        public static string Lable_CardNumber {
            get {
                return ResourceManager.GetString("Lable_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChequeBook Size.
        /// </summary>
        public static string Lable_ChequeBook_Size {
            get {
                return ResourceManager.GetString("Lable_ChequeBook_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declarant Number.
        /// </summary>
        public static string Lable_Declarnt {
            get {
                return ResourceManager.GetString("Lable_Declarnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declarnt Code.
        /// </summary>
        public static string Lable_DeclarntCode {
            get {
                return ResourceManager.GetString("Lable_DeclarntCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string Lable_ExpDate {
            get {
                return ResourceManager.GetString("Lable_ExpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Cheque Number.
        /// </summary>
        public static string Lable_From_Cheque_Number {
            get {
                return ResourceManager.GetString("Lable_From_Cheque_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date:.
        /// </summary>
        public static string Lable_FromDate {
            get {
                return ResourceManager.GetString("Lable_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPIN.
        /// </summary>
        public static string Lable_IPIN {
            get {
                return ResourceManager.GetString("Lable_IPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Lable_Month {
            get {
                return ResourceManager.GetString("Lable_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Transaction.
        /// </summary>
        public static string Lable_No_of_Trans {
            get {
                return ResourceManager.GetString("Lable_No_of_Trans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Number.
        /// </summary>
        public static string Lable_PolicyNo {
            get {
                return ResourceManager.GetString("Lable_PolicyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary File.
        /// </summary>
        public static string Lable_Salary_File {
            get {
                return ResourceManager.GetString("Lable_Salary_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Cheque Number.
        /// </summary>
        public static string Lable_To_Cheque_Number {
            get {
                return ResourceManager.GetString("Lable_To_Cheque_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Card.
        /// </summary>
        public static string Lable_ToCard {
            get {
                return ResourceManager.GetString("Lable_ToCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date:.
        /// </summary>
        public static string Lable_ToDate {
            get {
                return ResourceManager.GetString("Lable_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Lable_Year {
            get {
                return ResourceManager.GetString("Lable_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Succesful Login.
        /// </summary>
        public static string Last_Succesful_Login {
            get {
                return ResourceManager.GetString("Last_Succesful_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Unsuccesfull Logins.
        /// </summary>
        public static string Last_Unsuccesfull_Logins {
            get {
                return ResourceManager.GetString("Last_Unsuccesfull_Logins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to start your session.
        /// </summary>
        public static string loginBox {
            get {
                return ResourceManager.GetString("loginBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account.
        /// </summary>
        public static string Manage_Account {
            get {
                return ResourceManager.GetString("Manage_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Your Cards.
        /// </summary>
        public static string ManageCardsTitle {
            get {
                return ResourceManager.GetString("ManageCardsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your Meters.
        /// </summary>
        public static string ManageMetersTitle {
            get {
                return ResourceManager.GetString("ManageMetersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your Favorite Phones.
        /// </summary>
        public static string ManagePhonesTitle {
            get {
                return ResourceManager.GetString("ManagePhonesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message is Required.
        /// </summary>
        public static string MessageRequired {
            get {
                return ResourceManager.GetString("MessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Already Exists, Please add different Meter Number...
        /// </summary>
        public static string MeterAlreadyExistsError {
            get {
                return ResourceManager.GetString("MeterAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Fees.
        /// </summary>
        public static string MeterFees {
            get {
                return ResourceManager.GetString("MeterFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter ID.
        /// </summary>
        public static string MeterID {
            get {
                return ResourceManager.GetString("MeterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Name.
        /// </summary>
        public static string MeterName {
            get {
                return ResourceManager.GetString("MeterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Name is Required.
        /// </summary>
        public static string MeterNameRequired {
            get {
                return ResourceManager.GetString("MeterNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Number.
        /// </summary>
        public static string MeterNo {
            get {
                return ResourceManager.GetString("MeterNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Number is 11 digits long.
        /// </summary>
        public static string MeterNoLong {
            get {
                return ResourceManager.GetString("MeterNoLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ie: 04xxxxxxxxx.
        /// </summary>
        public static string MeterNoPlaceholder {
            get {
                return ResourceManager.GetString("MeterNoPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Number is Required.
        /// </summary>
        public static string MeterNoRequired {
            get {
                return ResourceManager.GetString("MeterNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Number.
        /// </summary>
        public static string MeterNumber {
            get {
                return ResourceManager.GetString("MeterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Number is Required.
        /// </summary>
        public static string MeterNumberRequired {
            get {
                return ResourceManager.GetString("MeterNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Bill Payment Service.
        /// </summary>
        public static string MobileBill_Payment_Service {
            get {
                return ResourceManager.GetString("MobileBill_Payment_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Bill Payment Service.
        /// </summary>
        public static string MobileBillPaymentService {
            get {
                return ResourceManager.GetString("MobileBillPaymentService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number Must be 12 Digits Long.
        /// </summary>
        public static string MobileLong {
            get {
                return ResourceManager.GetString("MobileLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number is Required.
        /// </summary>
        public static string MobileRequired {
            get {
                return ResourceManager.GetString("MobileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOHE.
        /// </summary>
        public static string MOHE {
            get {
                return ResourceManager.GetString("MOHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOHE Payment Service.
        /// </summary>
        public static string MOHE_BoxHeader {
            get {
                return ResourceManager.GetString("MOHE_BoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Number.
        /// </summary>
        public static string MOHE_StudentNo {
            get {
                return ResourceManager.GetString("MOHE_StudentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Number is Required.
        /// </summary>
        public static string MOHE_StudentNoRequired {
            get {
                return ResourceManager.GetString("MOHE_StudentNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Statement.
        /// </summary>
        public static string My_Statement {
            get {
                return ResourceManager.GetString("My_Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Transfers.
        /// </summary>
        public static string My_Transfers {
            get {
                return ResourceManager.GetString("My_Transfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Cheque Status.
        /// </summary>
        public static string MyChequeStatus {
            get {
                return ResourceManager.GetString("MyChequeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Transactions.
        /// </summary>
        public static string MyTransactions_BoxHeader {
            get {
                return ResourceManager.GetString("MyTransactions_BoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name  is Required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Net Amount.
        /// </summary>
        public static string NetAmount {
            get {
                return ResourceManager.GetString("NetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New IPIN.
        /// </summary>
        public static string NewIPIN {
            get {
                return ResourceManager.GetString("NewIPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New IPIN is Required.
        /// </summary>
        public static string NewIPINRequired {
            get {
                return ResourceManager.GetString("NewIPINRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Passowrd.
        /// </summary>
        public static string NewPassowrd {
            get {
                return ResourceManager.GetString("NewPassowrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plese Enter New Password.
        /// </summary>
        public static string NewPassowrdRequired {
            get {
                return ResourceManager.GetString("NewPassowrdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Rows.
        /// </summary>
        public static string NoOfRows {
            get {
                return ResourceManager.GetString("NoOfRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is No Recorded Transaction made with the selected Account.
        /// </summary>
        public static string noStatementRecords {
            get {
                return ResourceManager.GetString("noStatementRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Paid Amount.
        /// </summary>
        public static string NotPaidAmount {
            get {
                return ResourceManager.GetString("NotPaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter only numeric number.
        /// </summary>
        public static string NumericValidationError {
            get {
                return ResourceManager.GetString("NumericValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Message.
        /// </summary>
        public static string OperatorMsg {
            get {
                return ResourceManager.GetString("OperatorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own Transfer.
        /// </summary>
        public static string OwnTransferTitle {
            get {
                return ResourceManager.GetString("OwnTransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amount.
        /// </summary>
        public static string PaidAmount {
            get {
                return ResourceManager.GetString("PaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password is Required.
        /// </summary>
        public static string passwordRequired {
            get {
                return ResourceManager.GetString("passwordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Bill.
        /// </summary>
        public static string Pay_Bill_Button {
            get {
                return ResourceManager.GetString("Pay_Bill_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment_Parent {
            get {
                return ResourceManager.GetString("Payment_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Already Exists, Please add different Phone Number...
        /// </summary>
        public static string PhoneAlreadyExistsError {
            get {
                return ResourceManager.GetString("PhoneAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNo {
            get {
                return ResourceManager.GetString("PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number is Required.
        /// </summary>
        public static string PhoneNoRequired {
            get {
                return ResourceManager.GetString("PhoneNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount in SDG.
        /// </summary>
        public static string PlaceHolder_Amount {
            get {
                return ResourceManager.GetString("PlaceHolder_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter From Cheque Number....
        /// </summary>
        public static string PlaceHolder_from_chqNo {
            get {
                return ResourceManager.GetString("PlaceHolder_from_chqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPIN.
        /// </summary>
        public static string PlaceHolder_IPIN {
            get {
                return ResourceManager.GetString("PlaceHolder_IPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Account --.
        /// </summary>
        public static string PlaceHolder_Select_Account {
            get {
                return ResourceManager.GetString("PlaceHolder_Select_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Card --.
        /// </summary>
        public static string PlaceHolder_Select_Card {
            get {
                return ResourceManager.GetString("PlaceHolder_Select_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Number Of Transaction --.
        /// </summary>
        public static string PlaceHolder_Select_No_of_Trans {
            get {
                return ResourceManager.GetString("PlaceHolder_Select_No_of_Trans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter To Cheque Number....
        /// </summary>
        public static string PlaceHolder_to_chqNo {
            get {
                return ResourceManager.GetString("PlaceHolder_to_chqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Card Number.....
        /// </summary>
        public static string PlaceHolder_ToCard {
            get {
                return ResourceManager.GetString("PlaceHolder_ToCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Policy Number.
        /// </summary>
        public static string PolicyNoRequired {
            get {
                return ResourceManager.GetString("PolicyNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay for electricity bill quickly and easily.
        /// </summary>
        public static string QL_Electricity_info {
            get {
                return ResourceManager.GetString("QL_Electricity_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity Purchase.
        /// </summary>
        public static string QL_Electricity_Purchase {
            get {
                return ResourceManager.GetString("QL_Electricity_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchase your top-up with this service.
        /// </summary>
        public static string QL_Top_up {
            get {
                return ResourceManager.GetString("QL_Top_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchase your top-up with this service.
        /// </summary>
        public static string QL_TopupInfo {
            get {
                return ResourceManager.GetString("QL_TopupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to other account.
        /// </summary>
        public static string QL_Transfer {
            get {
                return ResourceManager.GetString("QL_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer funds from account to another with this service.
        /// </summary>
        public static string QL_Transfer_info {
            get {
                return ResourceManager.GetString("QL_Transfer_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links.
        /// </summary>
        public static string Quick_Links {
            get {
                return ResourceManager.GetString("Quick_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Transaction.
        /// </summary>
        public static string Radio_Number_Of_Transaction {
            get {
                return ResourceManager.GetString("Radio_Number_Of_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Radio_Period {
            get {
                return ResourceManager.GetString("Radio_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Number.
        /// </summary>
        public static string receiptNo {
            get {
                return ResourceManager.GetString("receiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciever Name.
        /// </summary>
        public static string RecieverName {
            get {
                return ResourceManager.GetString("RecieverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype New IPIN.
        /// </summary>
        public static string ReNewIPIN {
            get {
                return ResourceManager.GetString("ReNewIPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please RetypeNew IPIN .
        /// </summary>
        public static string ReNewIPINRequired {
            get {
                return ResourceManager.GetString("ReNewIPINRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string reNewPassowrd {
            get {
                return ResourceManager.GetString("reNewPassowrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string RequestedDate {
            get {
                return ResourceManager.GetString("RequestedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Size.
        /// </summary>
        public static string RequestedSize {
            get {
                return ResourceManager.GetString("RequestedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request New Cheque-Book.
        /// </summary>
        public static string RequestNewChequeBook_BoxHeader {
            get {
                return ResourceManager.GetString("RequestNewChequeBook_BoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a new Cheque.
        /// </summary>
        public static string RequestNewChequeTitle {
            get {
                return ResourceManager.GetString("RequestNewChequeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Transfer.
        /// </summary>
        public static string Salary_Transfer_Title {
            get {
                return ResourceManager.GetString("Salary_Transfer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Account Number.
        /// </summary>
        public static string SalaryAccountNo {
            get {
                return ResourceManager.GetString("SalaryAccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Account Type --.
        /// </summary>
        public static string SelectAccountType {
            get {
                return ResourceManager.GetString("SelectAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Branch --.
        /// </summary>
        public static string SelectBranch {
            get {
                return ResourceManager.GetString("SelectBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Currency --.
        /// </summary>
        public static string SelectCurrency {
            get {
                return ResourceManager.GetString("SelectCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Name.
        /// </summary>
        public static string SenderName {
            get {
                return ResourceManager.GetString("SenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send your Suggestions.
        /// </summary>
        public static string SendSuggestions {
            get {
                return ResourceManager.GetString("SendSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SendUs_Button {
            get {
                return ResourceManager.GetString("SendUs_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SendUs_Email {
            get {
                return ResourceManager.GetString("SendUs_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message...
        /// </summary>
        public static string SendUs_Message {
            get {
                return ResourceManager.GetString("SendUs_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string SendUs_Name {
            get {
                return ResourceManager.GetString("SendUs_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string SendUs_Subject {
            get {
                return ResourceManager.GetString("SendUs_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Us a Message.
        /// </summary>
        public static string SendUsMessageTitle {
            get {
                return ResourceManager.GetString("SendUsMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send your Suggestions.
        /// </summary>
        public static string SendYourSuggestion {
            get {
                return ResourceManager.GetString("SendYourSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services_Parent {
            get {
                return ResourceManager.GetString("Services_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string ShortAccountNumber {
            get {
                return ResourceManager.GetString("ShortAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject is Required.
        /// </summary>
        public static string SubjectRequired {
            get {
                return ResourceManager.GetString("SubjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        public static string SuccesHeader {
            get {
                return ResourceManager.GetString("SuccesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account has been Added successfully.
        /// </summary>
        public static string SuccessAccountMessage {
            get {
                return ResourceManager.GetString("SuccessAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Meter has been Added successfully.
        /// </summary>
        public static string SuccessMeterMessage {
            get {
                return ResourceManager.GetString("SuccessMeterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Favorite Phone has been Added successfully.
        /// </summary>
        public static string SuccessPhoneMessage {
            get {
                return ResourceManager.GetString("SuccessPhoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Contact For Support.
        /// </summary>
        public static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telecom Payment.
        /// </summary>
        public static string Telecom_Title {
            get {
                return ResourceManager.GetString("Telecom_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Account Number.
        /// </summary>
        public static string ToAccountNo {
            get {
                return ResourceManager.GetString("ToAccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To bank customer Transfer.
        /// </summary>
        public static string ToBankCustomer {
            get {
                return ResourceManager.GetString("ToBankCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Transfer.
        /// </summary>
        public static string ToCard_BoxHeader {
            get {
                return ResourceManager.GetString("ToCard_BoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Card.
        /// </summary>
        public static string ToCard_Title {
            get {
                return ResourceManager.GetString("ToCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Card Number.
        /// </summary>
        public static string ToCardNumber {
            get {
                return ResourceManager.GetString("ToCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter To Card Number.
        /// </summary>
        public static string ToCardNumberRequired {
            get {
                return ResourceManager.GetString("ToCardNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date is Required.
        /// </summary>
        public static string ToDateRequired {
            get {
                return ResourceManager.GetString("ToDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Branch Counter Transfer.
        /// </summary>
        public static string ToNonCustomer {
            get {
                return ResourceManager.GetString("ToNonCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top up Service.
        /// </summary>
        public static string Top_up_Service {
            get {
                return ResourceManager.GetString("Top_up_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Phone Number.
        /// </summary>
        public static string ToPhoneNo {
            get {
                return ResourceManager.GetString("ToPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Phone Number is Required.
        /// </summary>
        public static string ToPhoneNoRequired {
            get {
                return ResourceManager.GetString("ToPhoneNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string Total_Amount {
            get {
                return ResourceManager.GetString("Total_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Rows.
        /// </summary>
        public static string Total_Rows {
            get {
                return ResourceManager.GetString("Total_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Succesful Rows.
        /// </summary>
        public static string Total_Succesful_Rows {
            get {
                return ResourceManager.GetString("Total_Succesful_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Succesful Rows.
        /// </summary>
        public static string TotalSuccesfulRows {
            get {
                return ResourceManager.GetString("TotalSuccesfulRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction ID.
        /// </summary>
        public static string Transaction_ID {
            get {
                return ResourceManager.GetString("Transaction_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Name.
        /// </summary>
        public static string Transaction_Name {
            get {
                return ResourceManager.GetString("Transaction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Transaction_Status {
            get {
                return ResourceManager.GetString("Transaction_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string TransactionsTitle {
            get {
                return ResourceManager.GetString("TransactionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Transfer_Parent {
            get {
                return ResourceManager.GetString("Transfer_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Reference.
        /// </summary>
        public static string TransferReference {
            get {
                return ResourceManager.GetString("TransferReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbilled Amount.
        /// </summary>
        public static string unbilledAmount {
            get {
                return ResourceManager.GetString("unbilledAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units In Kwh.
        /// </summary>
        public static string UnitsInKwh {
            get {
                return ResourceManager.GetString("UnitsInKwh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Information.
        /// </summary>
        public static string Update_Information {
            get {
                return ResourceManager.GetString("Update_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update IPIN.
        /// </summary>
        public static string Update_IPIN_Title {
            get {
                return ResourceManager.GetString("Update_IPIN_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password.
        /// </summary>
        public static string Update_Password_Title {
            get {
                return ResourceManager.GetString("Update_Password_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER.
        /// </summary>
        public static string USER {
            get {
                return ResourceManager.GetString("USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name  is Required.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code is Required.
        /// </summary>
        public static string VerificationCodeRequired {
            get {
                return ResourceManager.GetString("VerificationCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Accounts.
        /// </summary>
        public static string View_Accounts {
            get {
                return ResourceManager.GetString("View_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Transactions.
        /// </summary>
        public static string View_All_Transactions {
            get {
                return ResourceManager.GetString("View_All_Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Statement.
        /// </summary>
        public static string View_Statement {
            get {
                return ResourceManager.GetString("View_Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Cheques.
        /// </summary>
        public static string ViewChequesTitle {
            get {
                return ResourceManager.GetString("ViewChequesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Investment.
        /// </summary>
        public static string ViewInvestment {
            get {
                return ResourceManager.GetString("ViewInvestment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Statement.
        /// </summary>
        public static string ViewStatementBtn {
            get {
                return ResourceManager.GetString("ViewStatementBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Information.
        /// </summary>
        public static string Voucher_Information {
            get {
                return ResourceManager.GetString("Voucher_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Fees.
        /// </summary>
        public static string WaterFees {
            get {
                return ResourceManager.GetString("WaterFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Information.
        /// </summary>
        public static string Your_Information {
            get {
                return ResourceManager.GetString("Your_Information", resourceCulture);
            }
        }
    }
}
